//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bank()
        {
            this.ActivityItem = new HashSet<ActivityItem>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Tel { get; set; }
        public string Url { get; set; }
        public string CoBranderCheckCode { get; set; }
        public string OPExchangeState { get; set; }
        public string Notice { get; set; }
        public bool IsDisabled { get; set; }
        public int Sort { get; set; }
        public string XLImageFileName { get; set; }
        public string SImageFileName { get; set; }
        public string CrystalImageFileName { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string LastUpdateUserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityItem> ActivityItem { get; set; }
    }
}
