//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.ActivityItem = new HashSet<ActivityItem>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public int BannerType { get; set; }
        public int BrandID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool ShowOnFrontPageBanner { get; set; }
        public bool ShowOnExchangeBanner { get; set; }
        public bool ShowOnBrandBanner { get; set; }
        public bool ShowOnOverviewBanner { get; set; }
        public string URI { get; set; }
        public string Content { get; set; }
        public string Notice { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<int> FrontPageSort { get; set; }
        public Nullable<int> ExchangeSort { get; set; }
        public Nullable<int> BrandSort { get; set; }
        public Nullable<int> OverviewSort { get; set; }
        public Nullable<int> StrategySort { get; set; }
        public int VerifyType { get; set; }
        public string CarousellImageFileName { get; set; }
        public string OverviewImageFileName { get; set; }
        public string LastUpdateUserName { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public System.DateTime CreateUpdateTime { get; set; }
        public string CreateUpdateUserName { get; set; }
        public Nullable<int> CollectCategoryID { get; set; }
        public string RewardCode { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityItem> ActivityItem { get; set; }
    }
}
