//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ActivityItem = new HashSet<ActivityItem>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public int BrandID { get; set; }
        public string ListPrice { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Notice { get; set; }
        public string Specification { get; set; }
        public string SImageFileName { get; set; }
        public string XLImageFileName { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string LastUpdateUserName { get; set; }
        public System.DateTime CreateUpdateTime { get; set; }
        public string CreateUpdateUserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityItem> ActivityItem { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
    }
}
