//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberVoucherBase
    {
        public string TransactionID { get; set; }
        public System.DateTime ExchangeDate { get; set; }
        public string VoucherHeaderCode { get; set; }
        public string PinCode { get; set; }
        public string BarCode1 { get; set; }
        public string BarCode2 { get; set; }
        public string MID { get; set; }
        public string VCode { get; set; }
        public int VoucherType { get; set; }
        public decimal AdditionalCharges { get; set; }
        public string ActivityItemCode { get; set; }
        public System.DateTime ExchangeStartDate { get; set; }
        public System.DateTime ExchangeEndDate { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string UsedStoreCode { get; set; }
        public string UsedStoreName { get; set; }
        public bool IsShared { get; set; }
        public Nullable<System.DateTime> SharedDate { get; set; }
        public string SharedToMid { get; set; }
        public string SharedToPhone { get; set; }
        public string SharedToEmail { get; set; }
        public int PointType { get; set; }
        public string VoucherBarcodeType { get; set; }
    }
}
