//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SETOPEntities : DbContext
    {
        public SETOPEntities()
            : base("name=SETOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityItem> ActivityItem { get; set; }
        public virtual DbSet<ActivityItemVoucher> ActivityItemVoucher { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetRolesDataRange> AspNetRolesDataRange { get; set; }
        public virtual DbSet<AspNetRolesPageAuth> AspNetRolesPageAuth { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUsersDataRange> AspNetUsersDataRange { get; set; }
        public virtual DbSet<AspNetUsersPageAuth> AspNetUsersPageAuth { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CompareString> CompareString { get; set; }
        public virtual DbSet<ExchangeCondition> ExchangeCondition { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<MemberFavoriteActivityItem> MemberFavoriteActivityItem { get; set; }
        public virtual DbSet<OpenPointMemberStar> OpenPointMemberStar { get; set; }
        public virtual DbSet<PageContent> PageContent { get; set; }
        public virtual DbSet<RewardActivity> RewardActivity { get; set; }
        public virtual DbSet<StopMachine> StopMachine { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TempVoucherHeader> TempVoucherHeader { get; set; }
        public virtual DbSet<VoucherHeader> VoucherHeader { get; set; }
    }
}
