//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Demo.DataBase.SETOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public string GUID { get; set; }
        public string TransactionID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime TradeTime { get; set; }
        public string MID { get; set; }
        public string VCode { get; set; }
        public string ActivityItemCode { get; set; }
        public string ActivityItemName { get; set; }
        public bool IsFirstGift { get; set; }
        public string RewardCode { get; set; }
        public int ExchangeQty { get; set; }
        public int ExchangeType { get; set; }
        public int PointType { get; set; }
        public int PerExchangePoint { get; set; }
        public decimal PerExchangeCash { get; set; }
        public string OLTPGetPointResultJSON { get; set; }
        public string OLTPDeductPointResultJSON { get; set; }
        public string OLTPCancelDeductPointResultJSON { get; set; }
        public bool HaveToReCancel { get; set; }
        public int TradeResultType { get; set; }
        public string Log { get; set; }
        public int CancelRetryTimes { get; set; }
    }
}
